package school_admission_system.entity;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name = "courses")
public class Course {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name; // Course name
    private String department; // Department name
    private String description; // Description of the course

    // Constructors, Getters, and Setters can be generated by Lombok
}
